Repository ili0n/Shuttle-front, pull requests merged in 2022-12, with the labels that each got.

#7 Feat/implement login frontend
  Shuttle-front/src/app/app-routing.module.ts
  Shuttle-front/src/app/app.component.html
  Shuttle-front/src/app/app.component.ts
  Shuttle-front/src/app/app.module.ts
  Shuttle-front/src/app/login/component/login/login.component.css
  Shuttle-front/src/app/login/component/login/login.component.html
  Shuttle-front/src/app/login/component/login/login.component.spec.ts
  Shuttle-front/src/app/login/component/login/login.component.ts
  Shuttle-front/src/environments/environment.ts
  Shuttle-front/src/infrastructure/app-routing.module.ts
  Shuttle-front/src/infrastructure/material.module.ts
  Shuttle-front/src/styles.css
Labels: enhancement

#8 Feat/navbar
  Shuttle-front/angular.json
  Shuttle-front/src/app/app.component.html
  Shuttle-front/src/app/app.component.ts
  Shuttle-front/src/app/app.module.ts
  Shuttle-front/src/app/navbar/navbar.component.css
  Shuttle-front/src/app/navbar/navbar.component.html
  Shuttle-front/src/app/navbar/navbar.component.spec.ts
  Shuttle-front/src/app/navbar/navbar.component.ts
  package-lock.json
Labels: enhancement

#14 Feat/4.4 implement forgot password component
  Shuttle-front/src/app/app.component.html
  Shuttle-front/src/app/app.module.ts
  Shuttle-front/src/app/login/component/forgot-password/forgot-password.component.css
  Shuttle-front/src/app/login/component/forgot-password/forgot-password.component.html
  Shuttle-front/src/app/login/component/forgot-password/forgot-password.component.spec.ts
  Shuttle-front/src/app/login/component/forgot-password/forgot-password.component.ts
  Shuttle-front/src/app/login/component/login/login.component.html
  Shuttle-front/src/app/login/component/login/login.component.ts
  Shuttle-front/src/app/login/component/reset-password/reset-password.component.css
  Shuttle-front/src/app/login/component/reset-password/reset-password.component.html
  Shuttle-front/src/app/login/component/reset-password/reset-password.component.spec.ts
  Shuttle-front/src/app/login/component/reset-password/reset-password.component.ts
  Shuttle-front/src/app/navbar/navbar.component.ts
  Shuttle-front/src/app/shared/shared.module.ts
  Shuttle-front/src/app/shared/shared.service.spec.ts
  Shuttle-front/src/app/shared/shared.service.ts
  Shuttle-front/src/app/shared/snack-bar/snack-bar.component.css
  Shuttle-front/src/app/shared/snack-bar/snack-bar.component.html
  Shuttle-front/src/app/shared/snack-bar/snack-bar.component.spec.ts
  Shuttle-front/src/app/shared/snack-bar/snack-bar.component.ts
  Shuttle-front/src/app/shared/validators/EqualsValidator.ts
  Shuttle-front/src/infrastructure/app-routing.module.ts
  Shuttle-front/src/infrastructure/material.module.ts
  Shuttle-front/src/styles.css
Labels: enhancement

#16 Feat/4.5 implement driver creation
  Shuttle-front/src/app/admin/admin.module.ts
  Shuttle-front/src/app/admin/create-driver/create-driver.component.css
  Shuttle-front/src/app/admin/create-driver/create-driver.component.html
  Shuttle-front/src/app/admin/create-driver/create-driver.component.spec.ts
  Shuttle-front/src/app/admin/create-driver/create-driver.component.ts
  Shuttle-front/src/app/app.module.ts
  Shuttle-front/src/app/login/component/reset-password/reset-password.component.ts
  Shuttle-front/src/assets/pfp_default.png
  Shuttle-front/src/infrastructure/app-routing.module.ts
  Shuttle-front/src/infrastructure/material.module.ts
Labels: enhancement

#21 Integration/2.2.6 admin create driver and vehicle
  Shuttle-front/src/app/admin/create-driver/create-driver.component.ts
  Shuttle-front/src/app/driver/driver.service.spec.ts
  Shuttle-front/src/app/driver/driver.service.ts
  Shuttle-front/src/app/driver/driver/driver.module.ts
  Shuttle-front/src/app/vehicle/vehicle.service.spec.ts
  Shuttle-front/src/app/vehicle/vehicle.service.ts
  Shuttle-front/src/app/vehicle/vehicle/vehicle.module.ts
Labels: integration

#25 Feat/2.5.1 driver new ride notification
  Shuttle-front/.editorconfig
  Shuttle-front/angular.json
  Shuttle-front/package-lock.json
  Shuttle-front/package.json
  Shuttle-front/src/app/app.module.ts
  Shuttle-front/src/app/driver/driver-home/driver-home.component.css
  Shuttle-front/src/app/driver/driver-home/driver-home.component.html
  Shuttle-front/src/app/driver/driver-home/driver-home.component.spec.ts
  Shuttle-front/src/app/driver/driver-home/driver-home.component.ts
  Shuttle-front/src/app/driver/reject-ride-dialog/reject-ride-dialog.component.css
  Shuttle-front/src/app/driver/reject-ride-dialog/reject-ride-dialog.component.html
  Shuttle-front/src/app/driver/reject-ride-dialog/reject-ride-dialog.component.spec.ts
  Shuttle-front/src/app/driver/reject-ride-dialog/reject-ride-dialog.component.ts
  Shuttle-front/src/app/passenger/passenger.module.ts
  Shuttle-front/src/app/passenger/passenger.service.spec.ts
  Shuttle-front/src/app/passenger/passenger.service.ts
  Shuttle-front/src/app/util/dom-util.ts
  Shuttle-front/src/assets/ico_baby.png
  Shuttle-front/src/assets/ico_pet.png
  Shuttle-front/src/infrastructure/app-routing.module.ts
  Shuttle-front/src/infrastructure/material.module.ts
  Shuttle-front/src/styles.css
Labels: enhancement, styling, component, integration

#26 Feat/2.5.2 driver reject ride
  Shuttle-front/src/app/driver/driver-home/driver-home.component.html
  Shuttle-front/src/app/driver/driver-home/driver-home.component.ts
  Shuttle-front/src/app/ride/ride.module.ts
  Shuttle-front/src/app/ride/ride.service.spec.ts
  Shuttle-front/src/app/ride/ride.service.ts
Labels: component, integration

#29 Feat/2.7.1 driver finish ride
  Shuttle-front/src/app/driver/driver-home/driver-home.component.ts
  Shuttle-front/src/app/ride/ride.service.ts
Labels: enhancement

#38 Feat/5.3.1 sockets for driver ride notifications
  Shuttle-front/package-lock.json
  Shuttle-front/package.json
  Shuttle-front/src/app/auth/auth.service.ts
  Shuttle-front/src/app/driver/driver-home/driver-home.component.html
  Shuttle-front/src/app/driver/driver-home/driver-home.component.ts
  Shuttle-front/src/index.html
Labels: integration
